# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  "Python 2.7":
    build:
      docker:
        - image: circleci/python:2.7.15
        - image: circleci/postgres:9.4

      working_directory: ~/repo

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

        - run:
            name: install dependencies
            command: |
              pip install virtualenv
              virtualenv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
          
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              python manage.py test

        - store_artifacts:
            path: test-reports
            destination: test-reports

  "Python 3.5":
    build:
      docker:
        - image: circleci/python:3.5.3
        - image: circleci/postgres:9.4

      working_directory: ~/repo

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt

        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
          
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              python manage.py test

        - store_artifacts:
            path: test-reports
            destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - "Python 2.7"
      - "Python 3.5"
