---
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
      - image: circleci/postgres:9.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "mws/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install -r mws/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "mws/requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd mws
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
